### PR TITLE
Feature/model path

### PR DESCRIPTION
**Pull request by Landsi**
As I am using Sourcery alongside this handy tool, i was missing a few stencil capabilities i got used to there.

So i updated the Renderer to use StencilSwiftKit. This adds a few new cool filters to be used in the templates.

Also, i added the modelName to be available in the template as a variable. 

Awesome tool, btw.

### CODE REVIEW

**Comment by Igor-Palaguta** [comment]
Cool! Let me check this

Thanks!

**Comment by Landsi** [comment]
fyi, this repo is featured ;) 
https://www.runtastic.com/blog/en/database-layer-on-ios/
see the "Automation" section

**Comment by Igor-Palaguta** [comment]
Nice! Thanks it is good sign I should review you PR faster!

Thanks

**Comment by Igor-Palaguta** [comment]
@Landsi 

Updated StencilSwiftKit and added modelName.

Please can you check 0.4.2

https://github.com/Igor-Palaguta/MotoSwift/releases

Thanks!

**Pull request closed without merging**
